# --- MAPPO specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel_continual"

buffer_size: 10
batch_size_run: 10
batch_size: 10

# update the target network every {} training steps
target_update_interval_or_tau: 0.01

lr: 0.0005
hidden_dim: 256

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

agent_output_type: "pi_logits"
learner: "ppo_learner"
entropy_coef: 0.001
use_rnn: False
standardise_returns: False
standardise_rewards: True
q_nstep: 5 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic"
epochs: 5
eps_clip: 0.2
name: "mappo"

# Continual task
run_continual: True
checkpoint_path: "results/models/mappo_seed291604234_cluster-default_2025-05-15 11:26:12.156367"
c_tasks: ['cluster-default','walker-limited_all']
